In [1]:
import torch

# The parity check matrix

n = 3
H = torch.zeros((n-1, n))
for i in range(n-1):
    H[i, i] += 1
    H[i, i+1] += 1

# The error syndrome

s = torch.tensor([[1],
                  [1]], dtype=torch.float32)

# Error probability

p = 0.01

rand1 = torch.rand(1).item()
rand2 = torch.rand(1).item()

# Prior LLR

l = torch.tensor([torch.log(torch.tensor((1-p) / p)) for i in range(n)])

# Maximum iterations

max_iterations = 10

# Messages initialisations

arr = []
qc_msg = H * l

# Iterative message passing

for i in range(20):
    
    # Check to qubit messages
    
    divide = torch.tanh(qc_msg/2)
    divide[divide==0] = 1
    cq_msg = 2*torch.atanh(torch.prod(divide, dim=1, keepdim=True) / divide)
    cq_msg /= 1.1
    cq_msg = cq_msg * H
    cq_msg = cq_msg * ((-1) ** s)

    
    # Qubit to check messages
    
    qc_msg = H * l
    print(torch.sum(cq_msg, dim=0, keepdim=True))
    qc_msg += torch.sum(cq_msg, dim=0, keepdim=True)
    qc_msg /= 1.1
    qc_msg = qc_msg * H
    qc_msg -= cq_msg
    
    
    # Beliefs

    beliefs = torch.sum(cq_msg, dim=0) + l
    arr.append(beliefs)

arr = torch.stack(arr)
print(arr)


tensor([[-4.1774, -8.3548, -4.1774]])
tensor([[-0.6905, -8.2857, -0.6905]])
tensor([[-0.7162, -7.7094, -0.7162]])
tensor([[-0.9305, -7.7136, -0.9305]])
tensor([[-0.9289, -7.7490, -0.9289]])
tensor([[-0.9157, -7.7488, -0.9157]])
tensor([[-0.9158, -7.7466, -0.9158]])
tensor([[-0.9167, -7.7466, -0.9167]])
tensor([[-0.9166, -7.7468, -0.9166]])
tensor([[-0.9166, -7.7468, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[-0.9166, -7.7467, -0.9166]])
tensor([[ 0.4177, -3.7596,  0.4177],
        [ 3.9046, -3.6906,  3.9046],
        [ 3.8790, -3.1142,  3.8790],
        [ 3.6646, -3.1185,  3.6646],
        [ 3.6662, -3.1539,  3.6662],
        [ 3.6794, -3.1537,  3.6794],
        [ 3.6793, 